// Code generated by MJML on 2020-10-13 18:13:38.400932 +0000 UTC, DO NOT EDIT.

package emails

//go:generate go run generate.go

import (
	"bytes"
	"html/template"
)

const (
	Success = ``

	Failure = ``

	Verify = ``

	ForgotPassword = ``

	Message = ``

	Transaction = ``

)

// Parse accepts a HTML template and data to render into the template
func Parse(temp string, data interface{}) (string, error) {
	var err error
	tmpl := template.New("email").Option("missingkey=error")
	tmpl, err = tmpl.Parse(temp)
	if err != nil {
		return "", err
	}
	w := bytes.NewBufferString("")
	if err := tmpl.Execute(w, data); err != nil {
		return "", err
	}
	return w.String(), nil
}
