package main

//go:generate go run generate.go

import (
	"bytes"
	"fmt"
	"github.com/statping/statping/utils"
	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/html"
	"io/ioutil"
	"os"
	"os/exec"
)

func main() {
	fmt.Println("Generating success/failure email templates from MJML to a HTML golang constant")

	success := convertMJML("success.mjml")
	failure := convertMJML("failure.mjml")
	verify := convertMJML("verify.mjml")

	htmlOut := `// Code generated by MJML on ` + utils.Now().String() + `, DO NOT EDIT.

package emails

const (
	` + constVar("Success", success) + `
	` + constVar("Failure", failure) + `
	` + constVar("Verify", verify) + `
)
`

	utils.SaveFile("emails/rendered.go", []byte(htmlOut))

	fmt.Println("Email MJML to HTML const saved: emails/rendered.go")
}

func constVar(key, data string) string {
	return fmt.Sprintf("%s = `%s`\n", key, data)
}

func minimize(val string) string {
	m := minify.New()
	m.Add("text/html", &html.Minifier{
		KeepDefaultAttrVals: true,
	})
	s, err := m.String("text/html", val)
	if err != nil {
		panic(err)
	}
	return s
}

func convertMJML(file string) string {
	w := bytes.NewBufferString("")
	fmt.Println("mjml", file)
	cmd := exec.Command("mjml", "./mjml/"+file, "-s")
	cmd.Stdout = w
	cmd.Start()
	cmd.Wait()

	out := minimize(w.String())
	ioutil.WriteFile("./dist/"+file+".html", []byte(out), os.FileMode(0755))
	return out
}
